### ISSUE TITLE
Ring 3 & snapshot 

### ISSUE THREAD

**Issue by z33ma** [stevenflesch/ring-to-android-tv#10]
Is there a way to set when the snapshot is taken?, in my testing the ring shows what happens before I even pressed the doorbell, I was coming out of the field of view. Just looked like no was there. When the bell went off.

**Comment by stevenflesch** [comment]
There isn't a configuration option to determine when a snapshot is taken, but if you want to exclude asking for motion-generated snapshots, you can change the event code to simply return when there is a motion event and only generate snapshots when the door is pressed.

Complicating this is that battery-powered cameras often take longer to generate a snapshot, and sometimes do not generate a second snapshot when requested shortly after the first one, like you're seeing.

You could wrap the snapshot generation like this:

Before:
`const snapshotBuffer = await camera.getSnapshot().catch(error => {
                        console.log('[ERROR] Unable to retrieve snapshot because:' + error.message)
                    })`

After:
`if(ding.kind == 'motion') {
const snapshotBuffer = await camera.getSnapshot().catch(error => {
                        console.log('[ERROR] Unable to retrieve snapshot because:' + error.message)
                    })
}`

**Comment by z33ma** [comment]
Wow that perfect! thank you so much, will make that change, my new PI is on its way too so should see some performance increase too.
