### ISSUE TITLE
Send one camera to multiple Android TV's

### ISSUE THREAD

**Issue by kharder69** [stevenflesch/ring-to-android-tv#11]
Is it possible to send one camera screen shot to multiple Android TV's?

**Comment by stevenflesch** [comment]
> Is it possible to send one camera screen shot to multiple Android TV's?

Yep.  You would need to change the environment variable for `R2ATV_IP_ADDRESS` to an array and then encapsulate the `sendNotification` method to loop through the array to send a notification to each TV.  Maybe something like this?

```
async function sendNotification(title, message, imageFile, exitAfter = false) {
        tvIpAddress.foreach(function(entry) {
                const options = {
                    method: "POST",
                    url: "http://" + entry + ":7979/notify",
                    port: 7979,
                    headers: {
                        "Content-Type": "multipart/form-data"
                    },
                    formData: {
                        "duration": displayTime,
                        "position": 0,
                        "title": title,
                        "titleColor": "#0066cc",
                        "titleSize": 20,
                        "message": message,
                        "messageColor": "#000000",
                        "messageSize": 14,
                        "backgroundColor": "#ffffff",
                        "image": (imageFile == '') ? "" : fs.createReadStream(__dirname + '/' + imageFile),
                        "imageWidth": 640
                    }
                }

                // Fire off POST message to PiPup with 'request'
                request(options, function(err, res, body) {
                    if (err) {
                        console.log(`[ERROR] Error sending notification: ${title} - ${message}`)
                        console.log(err)
                        process.exitCode = 1
                    } else {
                        console.log(`Sent notification successfully: ${title} - ${message}`)
                    }
                    if (exitAfter) process.exit()
                })
            }
        }
```

**Comment by kharder69** [comment]
Great thanks for the quick response.

On Feb 1, 2021, at 1:14 PM, Steven Flesch <notifications@github.com<mailto:notifications@github.com>> wrote:



Is it possible to send one camera screen shot to multiple Android TV's?

Yep. You would need to change the environment variable for R2ATV_IP_ADDRESS to an array and then encapsulate the sendNotification method to loop through the array to send a notification to each TV. Maybe something like this?

async function sendNotification(title, message, imageFile, exitAfter = false) {
        tvIpAddress.foreach(function(entry) {
                const options = {
                    method: "POST",
                    url: "http://" + entry + ":7979/notify",
                    port: 7979,
                    headers: {
                        "Content-Type": "multipart/form-data"
                    },
                    formData: {
                        "duration": displayTime,
                        "position": 0,
                        "title": title,
                        "titleColor": "#0066cc",
                        "titleSize": 20,
                        "message": message,
                        "messageColor": "#000000",
                        "messageSize": 14,
                        "backgroundColor": "#ffffff",
                        "image": (imageFile == '') ? "" : fs.createReadStream(__dirname + '/' + imageFile),
                        "imageWidth": 640
                    }
                }

                // Fire off POST message to PiPup with 'request'
                request(options, function(err, res, body) {
                    if (err) {
                        console.log(`[ERROR] Error sending notification: ${title} - ${message}`)
                        console.log(err)
                        process.exitCode = 1
                    } else {
                        console.log(`Sent notification successfully: ${title} - ${message}`)
                    }
                    if (exitAfter) process.exit()
                })
            }
        }
