### ISSUE TITLE
"Unable to retrieve camera locations because: Response code 404"

### ISSUE THREAD

**Issue by TheSwede86** [stevenflesch/ring-to-android-tv#19]
Hello,

Just tried this project out for the first time, I understand this not actively maintained but posting here anyway;
```
$node app.js --test
Attempting to get demo snapshot...
Refresh Token Updated
[ERROR] Unable to retrieve camera locations because: Response code 404 (Not Found)
```

I created a Ring API-token and put it in the ".env"-file and the error seems to be more about it not being able to locate the various "locations" I have / that the ring-client-api tries to fetch.

I looked at the package version of "ring-client-api" and it is;
9.12.8 (Dec 05 2020); https://github.com/dgreif/ring/releases/tag/v9.12.8
whereas the latest as of Jan 14 2021 is 9.23.0; https://github.com/dgreif/ring/releases/tag/v9.23.0

I am guessing the latest version of "ring-client-api" might solve this but I also guess that "ring-to-android-tv" needs to be changed as well? I don't know anything about node.js otherwise I would happily help.

Best Regards - Karl

**Comment by durag5** [comment]
I just changed the package version to the correct version and everything
worked again. Sorry I forgot to update. I actually moved away from it now
as I can replicate this action on Home Assistant and to more than just
android TV's.

**Comment by TheSwede86** [comment]
> I just changed the package version to the correct version and everything worked again. Sorry I forgot to update. I actually moved away from it now as I can replicate this action on Home Assistant and to more than just android TV's.

Thanks so much!

Yeah it works now, ran into a problem w. my "Ring View Door Cam";

```
[Fri Jan 14 2022 21:00:39 GMT+0100 (Central European Standard Time)] Doorbell pressed on Front Door camera.
[ERROR] Unable to retrieve snapshot because:Motion detection is disabled for Front Door, which prevents snapshots from this camera.  This can be caused by Modes settings or by turning off the Record Motion setting.

Snapshot saved!
Sent notification successfully: Doorbell Ring - Doorbell rung at Front Door!
```
Did not receive a notification on my TV since I guess there wasn't a snapshot to post.

Guessing this is something I should post in the "[ring-client-api](https://github.com/dgreif/ring/)"-repo?
I live in an apartment on the second floor of a third floor building and due to privacy (and a lot of worthless notifications when neighbors go up/down etc.) I haven't activated motion detection.

Would be great to get the snapshot of the recorded event when a guest presses the button (i.e. w.o enabling motion-detection)

Best Regards - Karl

**Comment by durag5** [comment]
That can be done in Home Assistant. I have it for motion and doorbell. You
could do just one or the other though. Not sure that would be in the scope
of this project. Also like you said I don't think anyone is going to
maintain this any longer.

**Comment by stevenflesch** [comment]
If you create a PR with the updated version I'd be happy to merge it. I unfortunately moved to a location without a Ring camera, so I'm unable to troubleshoot myself!

**Comment by TheSwede86** [comment]
> That can be done in Home Assistant. I have it for motion and doorbell. You
could do just one or the other though. Not sure that would be in the scope
of this project. Also like you said I don't think anyone is going to
maintain this any longer.

Sadly I don't have any Apple-devices and run Android  / Google Home.

> If you create a PR with the updated version I'd be happy to merge it. I unfortunately moved to a location without a Ring camera, so I'm unable to troubleshoot myself!

I'll happily do that tomorrow.

**Comment by durag5** [comment]
Home Assistant is smart assistant agnostic.

https://www.home-assistant.io/

**Comment by TheSwede86** [comment]
> Home Assistant is smart assistant agnostic.
> 
> https://www.home-assistant.io/

Ah sorry I got it mixed together w. Apple's HomeKit!
Ty will check it out

**Comment by stevenflesch** [comment]
Thank you for the PR!
