### ISSUE TITLE
Synology / docker support

### ISSUE THREAD

**Issue by dannyspanish** [stevenflesch/ring-to-android-tv#5]
Hi,

I came across your script on Reddit and can't wait to get started. It's exactly what I need. I have a Synology nas running Node v6. I've tried installing your program by following your instructions but I'm getting stuck on the npx part. I've had a quick look on Google and it looks like npx isn't available to Synology devices.

Running `sudo npm install -g npx ` doesn't work :sob:

I wondered if anyone else has successfully got it working on their device? or would creating a docker container be a possibility?

**Comment by stevenflesch** [comment]
Are you able to get an auth token using python on your Synology?

Maybe try the instructions listed here?
[https://github.com/tchellomello/python-ring-doorbell](https://github.com/tchellomello/python-ring-doorbell)

If that works,  I could update the README to list that as an alternative method.  From there, I'd leave it up to someone with better knowledge of docker to make a script to include.

**Comment by dannyspanish** [comment]
Thanks for getting back to me. I've taken a different approach and created a Ubuntu virtual server. I can finally use npx 👏  

I've created a file called token.txt in the root folder ring-to-android-tv with my access token but when I run  `node snapshot.js` the program is unable to connect to ring servers: 

> UnhandledPromiseRejectionWarning: Error: Refresh token is not valid.  Unable to authenticate with Ring servers.

Any ideas?

**Comment by stevenflesch** [comment]
Is the token copied with no quotes?

**Comment by dannyspanish** [comment]
> Is the token copied with no quotes?

Yes

**Comment by dannyspanish** [comment]
Sorry that was very abrupt. I'm wondering do you have 2FA enabled? If so via email or text?

**Comment by stevenflesch** [comment]
Oh, no worries!  I have 2FA enabled via text.  I haven't tested it without 2FA enabled, as it's on by default now, I believe.

**Comment by dannyspanish** [comment]
I'll change mine to text and see if that helps.

**Comment by dannyspanish** [comment]
Same outcome. Perhaps it's related to this: https://github.com/dgreif/ring/issues/279 if the refresh token can only be used once would that mean it's expired when your program tries to use it?

**Comment by dannyspanish** [comment]
All up and running 😃 

It was a couple of things: 

1) I didn't enter the token correctly, I had the token on 4 lines, not 1.
2) The Ring service was broken, to get it working I logged all of my devices out, logged in via the browser and re-issued a new token (I had to do this twice, the first one expired again after one use)

Thanks for your help.
