### ISSUE TITLE
Time Delay for the snapshot to be displayed

### ISSUE THREAD

**Issue by z33ma** [stevenflesch/ring-to-android-tv#9]
Got this working perfectly on my Raspberry Pi Zero and there is about a min time delay between button pressed and showing on the tv, not sure if this is due to the underpowered Raspberry Pi? 

thanks again, amazing work

**Comment by stevenflesch** [comment]
Have you tried changing `cameraDingsPollingSeconds` to something less than 5?  That's all I can think of, you might be better served optimizing node in general. Not sure if the W uses swap by default, etc.  Let me know if you are able to get the response time down!

**Comment by z33ma** [comment]
Thanks for the reply, all signs point to the node installation, will grab a faster PI and test it out. Currently getting about 43seconds from ring to display on the tv. What sort of time should I expecting?

**Comment by stevenflesch** [comment]
I have tested it on a Raspberry Pi 1, and an x86 thin client. Both respond within 10 seconds on my tests.

**Comment by z33ma** [comment]
That’s pretty good times, will test on my laptop and see what I get then look to switch to a faster pi. Thanks again
